- _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${general.optimizer_goal}
  patience: 3 
  mode: min
  check_on_train_epoch_end: False 

- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${general.optimizer_goal}
  save_top_k : 1
  mode: min
  dirpath: ${hydra:run.dir}
  filename: mode=${model.mode}-{epoch:02d}